server:
  port: 8085

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth-service/**
          filters:
            - RewritePath=/api/auth-service/(?<segment>.*), /api/v1/${segment}
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/product-service/**
          filters:
            - RewritePath=/api/product-service/(?<segment>.*), /api/v1/${segment}
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/order-service/**
          filters:
            - RewritePath=/api/order-service/(?<segment>.*), /api/v1/${segment}
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/payment-service/**
          filters:
            - RewritePath=/api/payment-service/(?<segment>.*), /api/v1/${segment}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG

jwt:
  secret:
    key: wJalrXUtnFEMIksbdfjhcvhs876bh6875efr556/K7MDENG/bPxRfiCYEXAMPLEKEY

auth:
  public-paths:
    - /api/auth-service/auth/login
    - /api/auth-service/auth/register
    - actuator/health